# Generated by Django 5.0.6 on 2024-06-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='Technologies',
        ),
        migrations.AddField(
            model_name='experience',
            name='Technologies',
            field=models.ManyToManyField(related_name='experience_technology', to='base.tech'),
        ),
    ]
