# Generated by Django 5.0.6 on 2024-06-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_experience_technologies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='Technologies',
        ),
        migrations.AddField(
            model_name='projects',
            name='Technologies',
            field=models.ManyToManyField(related_name='project_technology', to='base.tech'),
        ),
    ]
