# Generated by Django 5.0.6 on 2024-06-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_projects_technologies_projects_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='Roles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
